const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript'),http=require('node:http');
const fixture=Uint8Array.from([0,255,128,42,0,255,1]);
function load(file,dependencies,globals={}){const filename=path.join(__dirname,'..',file);const js=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};vm.runInNewContext(js,{module,exports:module.exports,require:name=>dependencies[name],AbortController,setTimeout,clearTimeout,fetch,Uint8Array,FormData:class{constructor(){throw Error('Unsupported FormDataPart implementation');}},...globals});return module.exports;}
function uploader(options={}){const reads=[];const module=load('services/fileUpload.ts',{
 'react-native':{Platform:{OS:options.platform||'ios'}},
 'expo-file-system':{File:class{async base64(){reads.push('modern');if(options.readError)throw Error('denied');return options.empty?'':Buffer.from(fixture).toString('base64');}}},
 'expo-file-system/legacy':{EncodingType:{Base64:'base64'},readAsStringAsync:async()=>{reads.push('legacy');if(options.legacyError)throw Error('denied');return Buffer.from(fixture).toString('base64');}},
 'expo/fetch':{fetch:options.fetch||fetch},'./secureStorage':{getStoredToken:async()=>options.noToken?null:'test-token'},
},{fetch:options.fetch||fetch});return {upload:module.uploadFile,reads};}
test('iOS, Android and web round-trip JSON bytes without constructing FormData',async()=>{
 const received=[];const server=http.createServer(async(req,res)=>{if(req.url==='/source'){res.writeHead(200);res.end(fixture);return;}const chunks=[];for await(const chunk of req)chunks.push(chunk);received.push({headers:req.headers,payload:JSON.parse(Buffer.concat(chunks).toString())});res.writeHead(201,{'content-type':'application/json'});res.end(JSON.stringify({data:{url:'https://res.cloudinary.com/test/image/upload/id.jpg'}}));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{const base='http://127.0.0.1:'+server.address().port;for(const platform of ['ios','android','web']){const {upload}=uploader({platform});const r=await upload(base+'/upload','file',platform==='web'?base+'/source':'file:///document.pdf','document.pdf','application/pdf');assert.match(r.data.url,/^https:/);}for(const r of received){assert.equal(r.headers['content-type'],'application/json');assert.equal(r.headers.authorization,'Bearer test-token');assert.equal(r.payload.fieldName,'file');assert.equal(r.payload.mimeType,'application/pdf');assert.deepEqual(Buffer.from(r.payload.fileBase64,'base64'),Buffer.from(fixture));}}finally{await new Promise(resolve=>server.close(resolve));}
});
test('picker data bypasses unreadable URI and preserves avatar field',async()=>{let sent;const {upload,reads}=uploader({readError:true,legacyError:true,fetch:async(_url,options)=>{sent=JSON.parse(options.body);return new Response('{"data":{"avatarUrl":"https://res.cloudinary.com/test/image/upload/id.jpg"}}',{status:201});}});await upload('url','avatar','unreadable://image','photo.heic','image/heic','AP+AKg==');assert.equal(reads.length,0);assert.equal(sent.fieldName,'avatar');assert.equal(sent.fileName,'photo.jpg');assert.equal(sent.mimeType,'image/jpeg');});
test('uses original URI reader fallback without copying files',async()=>{const {upload,reads}=uploader({readError:true,fetch:async()=>new Response('{}',{status:201})});await upload('url','file','content://source');assert.deepEqual(reads,['modern','legacy']);});
test('fails clearly if both URI readers fail',async()=>{const {upload}=uploader({readError:true,legacyError:true});await assert.rejects(upload('url','file','uri'),/Could not read/);});
test('requires authentication before reading',async()=>{const {upload,reads}=uploader({noToken:true});await assert.rejects(upload('url','file','uri'),/Sign in/);assert.equal(reads.length,0);});
test('empty files are rejected',async()=>{await assert.rejects(uploader({empty:true}).upload('url','file','uri'),/empty/);});
for(const [status,body,expected] of [[401,'{}',/expired/],[413,'{}',/20 MB/],[502,'{"message":"Cloudinary upload failed"}',/Cloudinary/],[201,'html',/invalid response/]])test('handles response '+status+' '+body,async()=>{await assert.rejects(uploader({fetch:async()=>new Response(body,{status})}).upload('url','file','uri'),expected);});
test('secure Cloudinary URL required after upload',async()=>{const api=load('services/cloudinary.ts',{'./api':{API_BASE_URL:'url'},'./fileUpload':{uploadFile:async()=>({data:{url:'http://bad'}})}});await assert.rejects(api.uploadToCloudinary('uri'),/secure file link/);});
